apiVersion: customreplicaset.ishaan.microsoft/v1
kind: CustomReplicaSet
metadata: 
  name: customreplicaset-sample
spec: 
  replicas: 10
  template:
    metadata:
      labels:
        owner: "" # to be filled in during pod creation
        revision: "" # to be filled in during pod creation
    spec:
      restartPolicy: Never
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sleep", "3600"]
  partition: 7  # Number of upgraded pods
  revisionHistoryLimit: 20 # Max revision history stored