apiVersion: customreplicaset.ishaan.microsoft/v1
kind: CustomReplicaSet
metadata: 
  name: customreplicaset-sample
spec: 
  replicas: 8
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sleep", "3600"]
  partition: 5  # Number of upgraded pods
  revisionHistoryLimit: 20 # Max revision history stored
