apiVersion: customreplicaset.ishaan.microsoft/v1
kind: CustomReplicaSet
metadata: 
  name: customreplicaset-sample
spec: 
  replicas: 8
  template:
    # metadata:
    #   labels:
    #     app: my-app
    spec:
      restartPolicy: Never
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sleep", "3600"]
  partition: 5  # Number of upgraded pods
  revisionHistoryLimit: 20 # Max revision history stored

  # upgradedTemplate:
  #   apiVersion: v1
  #   kind: Pod
  #   metadata:
  #     labels:
  #       app: my-app2
  #   spec:
  #     restartPolicy: Never
  #     containers:
  #     - name: busybox
  #       image: busybox:latest
  #       command: ["sleep", "3600"]