apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customreplicasets.customreplicaset.ishaan.microsoft
spec:
  group: customreplicaset.ishaan.microsoft
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
              template:
                type: object
                x-kubernetes-embedded-resource: true
                x-kubernetes-preserve-unknown-fields: true
              upgradedReplicas: 
                type: integer
              # upgradedTemplate:
              #   type: object
              #   x-kubernetes-embedded-resource: true
              #   x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: customreplicasets
    singular: customreplicaset
    kind: CustomReplicaSet
    listKind: CustomReplicaSetList
