apiVersion: v1
kind: Pod
metadata:
  name: standard-busybox
  labels: 
    app: standard-busybox
spec: 
  restartPolicy: Never
  containers: 
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]