apiVersion: customreplicaset.ishaan.microsoft/v1
kind: CustomReplicaSet
metadata: 
  name: customreplicaset-sample
spec: 
  replicas: 3
  strategy: 
    partition: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nginx
          image: nginx:1.18