# permissions for end users to view customreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customreplicaset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd
    app.kubernetes.io/part-of: crd
    app.kubernetes.io/managed-by: kustomize
  name: customreplicaset-viewer-role
rules:
- apiGroups:
  - customreplicaset.ishaan.microsoft
  resources:
  - customreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - customreplicaset.ishaan.microsoft
  resources:
  - customreplicasets/status
  verbs:
  - get
