---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - customreplicaset.ishaan.microsoft
  resources:
  - customreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customreplicaset.ishaan.microsoft
  resources:
  - customreplicasets/finalizers
  verbs:
  - update
- apiGroups:
  - customreplicaset.ishaan.microsoft
  resources:
  - customreplicasets/status
  verbs:
  - get
  - patch
  - update
